# Similar to com.cisco.pt.ptmp.ConnectionNegotiationProperties
PTMP_IDENTIFIER = 'PTMP'
PTMP_VERSION = 1
PTMP_ENCODING_TEXT = 1
PTMP_ENCODING_BINARY = 2
PTMP_NO_ENCRYPTION = 1
PTMP_XOR_ENCRYPTION = 2
PTMP_NO_COMPRESSION = 1
PTMP_ZLIB_COMPRESSION = 2
PTMP_AUTHENTICATION_CLEAR_TEXT = 1
PTMP_AUTHENTICATION_SIMPLE = 2
PTMP_AUTHENTICATION_MD5 = 4
PTMP_KEEP_ALIVE = 0
PTMP_RESERVED = 0
# ToDo RESERVED in the Cisco doc is an empty string.  Revisit this.

# Models the abbreviated constants in com.cisco.pt.ipc.enums.PtmpTypeValue.java
PTMP_TYPE_VALUE_VOID = 0
PTMP_TYPE_VALUE_BYTE = 1
PTMP_TYPE_VALUE_BOOL = 2
PTMP_TYPE_VALUE_SHORT = 3
PTMP_TYPE_VALUE_INT = 4
PTMP_TYPE_VALUE_LONG = 6
PTMP_TYPE_VALUE_FLOAT = 6
PTMP_TYPE_VALUE_DOUBLE = 7
PTMP_TYPE_VALUE_QSTRING = 8
PTMP_TYPE_VALUE_STRING = 9
PTMP_TYPE_VALUE_TREENODE = 'TreeNode'
# The remainder have not been implemented

# Similar to ltv.java
PTMP_MESSAGE_TYPE_NEGOTIATION_REQUEST = 0
PTMP_MESSAGE_TYPE_NEGOTIATION_RESPONSE = 1
PTMP_MESSAGE_TYPE_AUTHENTICATION_REQUEST = 2
PTMP_MESSAGE_TYPE_AUTHENTICATION_CHALLENGE = 3
PTMP_MESSAGE_TYPE_AUTHENTICATION_RESPONSE = 4
PTMP_MESSAGE_TYPE_AUTHENTICATION_STATUS = 5
PTMP_MESSAGE_TYPE_KEEP_ALIVE = 6
PTMP_MESSAGE_TYPE_DISCONNECT = 7
PTMP_MESSAGE_TYPE_COMMUNICATION = 8
PTMP_MESSAGE_TYPE_IPC_MESSAGE = 100
PTMP_MESSAGE_TYPE_IPC_ERROR = 101
PTMP_MESSAGE_TYPE_IPC_RESPONSE = 102
PTMP_MESSAGE_TYPE_IPC_EVENT = 103
PTMP_MESSAGE_TYPE_IPC_EVENT_SUBSCRIPTION = 104
# Multi user constants not implemented

# From com.cisco.pt.PacketTracerConstants
# Not currently implemented
AUTH_SUCCESS = 1
AUTH_FAIL = 2

# Similar to com.cisco.pt.ipc.enums.FileOpenReturnValue
FILE_OPEN_OK = 0
FILE_OPEN_BAD_SSL = 1
FILE_OPEN_BAD_DECOMPRESS = 2
FILE_OPEN_BAD_BINARY = 3
FILE_OPEN_BAD_METAFILE = 4
FILE_OPEN_BAD_CONFIGURATION = 5
FILE_OPEN_UNABLE_TO_READ_FILE = 6
FILE_OPEN_BAD_OPTIONS = 7
FILE_OPEN_USER_CANCEL = 8

# Similar to com.cisco.pt.ipc.enums.DYNAMICTYPE
DYNAMIC_FEEDBACK_TYPE_NOFEEDBACK = 0
DYNAMIC_FEEDBACK_TYPE_PERCENTAGEPOINT = 1
DYNAMIC_FEEDBACK_TYPE_PERCENTAGESCORE = 2
DYNAMIC_FEEDBACK_TYPE_POINTS = 3
DYNAMIC_FEEDBACK_TYPE_SCORE = 4

# PTMP PDU response indices
APP_UUID_IDX = 4
CURRENT_TIME_IDX = 9
EXAPP_AUTHENTICATION_STATUS_IDX = 2
PTMP_ENCODING_TEXT_IDX = 5
PTMP_NO_ENCRYPTION_IDX = 6
PTMP_NO_COMPRESSION_IDX = 7
PTMP_AUTHENTICATION_MD5_IDX = 8
PTMP_IDENTIFIER_IDX = 2
PTMP_VERSION_IDX = 3
PTMP_KEEP_ALIVE_IDX = 10
PTMP_RESERVED_IDX = 11
PTMP_REPLY_LENGTH = 4
PTMP_REPLY_LENGTH_IDX = 0
PTMP_REPLY_TYPE_IDX = 1
PTMP_REPLY_MESSAGE_ID_IDX = 2
PTMP_REPLY_VALUE_TYPE_IDX = 3
PTMP_REPLY_VALUE_IDX = 4
PTMP_NO_CONFIRMATION = 'false'
PTMP_CONFIRMATION = 'true'
PTMP_EXAPP_CHALLENGE_IDX = 2

PTMP_MAX_BUFFER_SIZE = 1024
